// Confirmation words for pairing. Both phones derive the same index from the
// shared key and show the same word; partners compare it out loud. Words are
// short, concrete, and easy to say — nothing abstract or emotionally loaded.
export const CONFIRMATION_WORDS = [
  'acorn', 'almond', 'amber', 'anchor', 'apple', 'apricot', 'arch', 'aspen',
  'atlas', 'autumn', 'avocado', 'badger', 'bamboo', 'banjo', 'barley', 'basil',
  'beach', 'beacon', 'berry', 'birch', 'biscuit', 'blanket', 'bloom', 'blossom',
  'bluebell', 'boat', 'bonfire', 'book', 'boot', 'bramble', 'breeze', 'brick',
  'bridge', 'brook', 'bucket', 'butter', 'button', 'cabin', 'cactus', 'candle',
  'canoe', 'canvas', 'caramel', 'carrot', 'castle', 'cedar', 'cello', 'chalk',
  'cherry', 'chestnut', 'cinnamon', 'clover', 'cobble', 'cocoa', 'compass', 'copper',
  'coral', 'cotton', 'cradle', 'crayon', 'cricket', 'crumpet', 'crystal', 'cushion',
  'daisy', 'dew', 'dolphin', 'dune', 'eagle', 'ember', 'engine', 'fable',
  'falcon', 'feather', 'fern', 'fiddle', 'fig', 'finch', 'firefly', 'flint',
  'flute', 'fog', 'forest', 'fossil', 'fountain', 'fox', 'garden', 'garnet',
  'ginger', 'glacier', 'glade', 'goose', 'granite', 'grape', 'grove', 'guitar',
  'hammock', 'harbor', 'harvest', 'hazel', 'heather', 'hedgehog', 'heron', 'hill',
  'honey', 'horizon', 'iceberg', 'iris', 'island', 'ivory', 'ivy', 'jasmine',
  'jigsaw', 'juniper', 'kayak', 'kestrel', 'kettle', 'kite', 'ladder', 'lagoon',
  'lake', 'lantern', 'lavender', 'leaf', 'lemon', 'lighthouse', 'lilac', 'lily',
  'linen', 'lobster', 'log', 'lotus', 'magnet', 'mango', 'maple', 'marble',
  'meadow', 'melon', 'mint', 'mirror', 'mitten', 'moss', 'moth', 'mountain',
  'mulberry', 'mushroom', 'nectar', 'nest', 'nettle', 'north', 'nutmeg', 'oak',
  'oasis', 'oat', 'ocean', 'olive', 'onyx', 'opal', 'orange', 'orchard',
  'orchid', 'otter', 'owl', 'oyster', 'paddle', 'pantry', 'paper', 'parsley',
  'peach', 'pear', 'pebble', 'pecan', 'pelican', 'pencil', 'penguin', 'peony',
  'pepper', 'petal', 'piano', 'pigeon', 'pine', 'pistachio', 'plum', 'pocket',
  'polar', 'pond', 'poppy', 'porch', 'prairie', 'puffin', 'pumpkin', 'quartz',
  'quill', 'quilt', 'rabbit', 'raft', 'rain', 'raisin', 'raven', 'reef',
  'ribbon', 'river', 'robin', 'rocket', 'rope', 'rose', 'rowan', 'ruby',
  'saddle', 'saffron', 'sage', 'sail', 'salmon', 'sand', 'sapling', 'satchel',
  'seal', 'seed', 'shell', 'shore', 'silver', 'sky', 'sleigh', 'slipper',
  'snow', 'sock', 'sparrow', 'spice', 'spoon', 'spring', 'spruce', 'squirrel',
  'stone', 'stork', 'summer', 'sunflower', 'swan', 'sycamore', 'tangerine', 'teapot',
  'thistle', 'thyme', 'tiger', 'timber', 'toffee', 'tulip', 'turtle', 'umbrella',
  'valley', 'vanilla', 'velvet', 'vine', 'violet', 'walnut', 'wave', 'willow',
] as const;
